spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
---
spring:
  profiles: default

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bula_dev?useSSL=false
    username: root
    password: root

server:
  port: 9004
